(function(){
const A=InsurNex.auth,db=InsurNex.db,S=InsurNex.state,t=InsurNex.t,E=InsurNex.esc,D=InsurNex.fmtDate,M=InsurNex.fmtMoney,toast=InsurNex.toast,err=InsurNex.friendlyError;
let view=(location.hash||"#dashboard").slice(1),cache={};
const mod={
organizations:["Organizations",[["name","Company","text"],["legalName","Legal","text"],["ownerId","Owner","text"],["licenseNumber","License","text"],["status","Status","select","active,suspended"]]],
users:["Users",[["name","Name","text"],["email","Email","email"],["mobile","Mobile","tel"],["accountType","Account type","text"],["status","Status","select","active,suspended"]]],
brokerProfiles:["Brokers",[["userId","User","text"],["licenseNumber","License","text"],["specialization","Specialization","text"],["companyName","Company","text"],["status","Status","select","active,suspended"]]],
teams:["Teams",[["name","Name","text"],["managerName","Manager","text"],["description","Description","textarea"],["status","Status","select","active,inactive"]]],
insurers:["Insurers",[["name","Name","text"],["license","License","text"],["email","Email","email"],["phone","Phone","tel"],["website","Website","url"],["status","Status","select","active,inactive"]]],
insuranceProducts:["Products",[["name","Name","text"],["insuranceType","Type","text"],["insurer","Insurer","text"],["premiumRange","Premium range","text"],["commission","Commission","number"],["status","Status","select","active,inactive"]]],
plans:["Plans",[["name","Name","text"],["customerLimit","Customers","number"],["userLimit","Users","number"],["policyLimit","Policies","number"],["monthlyPrice","Monthly price","number"],["status","Status","select","active,inactive"]]],
subscriptions:["Subscriptions",[["ownerId","Owner","text"],["plan","Plan","select","Free,Professional,Business,Enterprise"],["status","Status","select","trial,active,pastDue,cancelled"],["renewalDate","Renewal","date"]]],
supportTickets:["Support",[["subject","Subject","text"],["priority","Priority","select","low,medium,high,urgent"],["status","Status","select","Open,In Progress,Waiting for User,Resolved,Closed"],["message","Message","textarea"]]],
knowledgeBase:["Knowledge Base",[["title","Title","text"],["category","Category","text"],["status","Status","select","draft,published"],["body","Body","textarea"]]],
announcements:["Announcements",[["title","Title","text"],["type","Type","text"],["status","Status","select","draft,published"],["body","Body","textarea"]]],
settings:["Settings",[["key","Key","text"],["value","Value","textarea"]]],
policies:["Policies",[["policyNumber","Policy","text"],["customerName","Customer","text"],["insurer","Insurer","text"],["product","Product","text"],["premium","Premium","number"],["expiryDate","Expiry","date"],["status","Status","select","Active,Expired,Cancelled,Suspended,Renewed"]]],
renewals:["Renewals",[["policyNumber","Policy","text"],["customerName","Customer","text"],["expiryDate","Expiry","date"],["stage","Stage","select","90 Days,60 Days,45 Days,30 Days,15 Days,7 Days,Expired"],["status","Status","select","Open,In Progress,Renewed,Lost,Expired"]]],
claims:["Claims",[["claimNumber","Claim","text"],["customerName","Customer","text"],["policyNumber","Policy","text"],["amount","Amount","number"],["status","Status","select","Reported,Under Review,Documents Required,Submitted,Under Assessment,Approved,Rejected,Settled,Closed"]]],
commissions:["Commissions",[["policyNumber","Policy","text"],["customerName","Customer","text"],["insurer","Insurer","text"],["premium","Premium","number"],["commissionAmount","Commission","number"],["status","Status","select","Expected,Pending,Approved,Paid,Cancelled"]]]
};
const nav=["dashboard","organizations","users","brokerProfiles","teams","insurers","insuranceProducts","plans","subscriptions","policies","renewals","claims","commissions","supportTickets","knowledgeBase","announcements","analytics","auditLogs","settings"];
function mark(){return '<div class="brand-mark image-mark" aria-label="InsurNex"><img src="assets/logo.svg" alt="InsurNex"></div>'}
function ico(n){return ({dashboard:"⌂",organizations:"🏢",users:"👤",brokerProfiles:"🪪",teams:"👨‍👩‍👧‍👦",insurers:"🏦",insuranceProducts:"📦",plans:"💳",subscriptions:"🔖",policies:"🛡️",renewals:"🔄",claims:"🧾",commissions:"💰",supportTickets:"🎧",knowledgeBase:"📚",announcements:"📢",analytics:"📊",auditLogs:"🔎",settings:"⚙️"}[n]||"•")}
function shell(){
  const links=nav.map(n=>'<a class="drawer-link" href="#'+n+'" data-nav="'+n+'"><span>'+ico(n)+' '+(mod[n]?mod[n][0]:(n==="auditLogs"?"Audit Logs":n==="analytics"?"Analytics":"Dashboard"))+'</span><span>›</span></a>').join("");
  document.getElementById("adminApp").innerHTML='<div class="app-shell"><aside class="desktop-drawer"><div class="drawer-head">'+mark()+' <strong>InsurNex Admin</strong></div>'+links+'<button class="btn btn-danger" id="logout" style="margin-top:12px">'+t("logout")+'</button></aside><main class="main"><header class="topbar"><div class="brand">'+mark()+'<div><div class="brand-name">InsurNex Admin</div><div class="subtitle">Platform administration</div></div></div><div class="actions"><span class="badge success">'+E(S.adminRole||"platformAdmin")+'</span><button class="btn" id="lang">AR/EN</button><button class="btn" id="menu">☰</button><button class="btn" id="logout2">⇥</button></div></header><section id="adminView" class="content"></section></main><div class="drawer" id="drawer"><div class="drawer-panel"><div class="drawer-head"><strong>InsurNex Admin</strong><button class="close" id="closeDrawer">×</button></div>'+links+'<button class="btn btn-danger" id="logout3" style="margin-top:12px">'+t("logout")+'</button></div></div></div>';
  document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=e=>{e.preventDefault();view=b.dataset.nav;location.hash=view;render();drawer(false)});
  document.getElementById("logout").onclick=logout;document.getElementById("logout2").onclick=logout;document.getElementById("logout3").onclick=logout;
  document.getElementById("menu").onclick=()=>drawer(true);document.getElementById("closeDrawer").onclick=()=>drawer(false);
  document.getElementById("lang").onclick=()=>{InsurNex.setLanguage(InsurNex.locale()==="ar"?"en":"ar");shell();render()};
}
function drawer(show){document.getElementById("drawer")?.classList.toggle("show",show)}
function login(message){
 document.getElementById("adminApp").innerHTML='<main class="auth-wrap"><section class="auth-card"><div class="auth-logo">'+mark()+'<div><div class="brand-name">InsurNex Admin</div><div class="subtitle">Restricted platform administration</div></div></div><h1 class="auth-title">'+t("login")+'</h1>'+(message?'<div class="error-box">'+E(message)+'</div>':'')+'<form id="adminLogin" class="form-stack"><div class="field"><label>'+t("email")+'</label><input name="email" type="email" required></div><div class="field"><label>'+t("password")+'</label><input name="password" type="password" required></div><button class="btn btn-primary">'+t("login")+'</button></form><div class="section-note" style="margin-top:12px">platformRole must be superAdmin or platformAdmin.</div></section></main>';
 document.getElementById("adminLogin").onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.currentTarget);await A.signInWithEmailAndPassword(String(f.get("email")).trim(),String(f.get("password")));await guard()}catch(x){login(err(x))}}
}
async function guard(){
 if(!A.currentUser){login();return}
 try{let r=(await A.currentUser.getIdTokenResult(true)).claims.platformRole;if(!["superAdmin","platformAdmin"].includes(r)){await A.signOut();login("الحساب لا يملك صلاحية InsurNex Admin.");return}S.user=A.currentUser;S.adminRole=r;shell();render()}catch(x){login(err(x))}
}
async function load(c){if(cache[c])return cache[c];let s=await db.collection(c).limit(100).get();return cache[c]=s.docs.map(d=>({id:d.id,...d.data()}))}
function invalidate(){cache={}}
async function dashboard(){
 let a=await Promise.all(["users","organizations","policies","claims","renewals","supportTickets","subscriptions","commissions"].map(load));
 let [u,o,p,c,r,s,sub,cm]=a, expected=cm.reduce((n,x)=>n+Number(x.commissionAmount||0),0),paid=cm.filter(x=>x.status==="Paid").reduce((n,x)=>n+Number(x.paidCommission||x.commissionAmount||0),0);
 return '<div class="page-head"><div><div class="eyebrow">InsurNex Admin</div><h1>Dashboard</h1><div class="muted">'+E(S.adminRole)+'</div></div></div><div class="stats"><div class="stat"><div class="value">'+u.length+'</div><div class="label">Users</div></div><div class="stat"><div class="value">'+o.length+'</div><div class="label">Organizations</div></div><div class="stat"><div class="value">'+p.length+'</div><div class="label">Policies</div></div><div class="stat"><div class="value">'+c.length+'</div><div class="label">Claims</div></div><div class="stat"><div class="value">'+r.length+'</div><div class="label">Renewals</div></div><div class="stat"><div class="value">'+s.length+'</div><div class="label">Support</div></div><div class="stat"><div class="value">'+sub.length+'</div><div class="label">Subscriptions</div></div><div class="stat"><div class="value">'+fmt(expected-paid)+'</div><div class="label">Pending commission</div></div></div><div class="grid grid-2" style="margin-top:14px"><div class="card"><h3>Commission control</h3><div class="list"><div class="list-row"><span>Expected</span><strong>'+fmt(expected)+'</strong></div><div class="list-row"><span>Paid</span><strong>'+fmt(paid)+'</strong></div><div class="list-row"><span>Pending</span><strong>'+fmt(Math.max(0,expected-paid))+'</strong></div></div></div><div class="card"><h3>Governance</h3><p class="section-note">Platform administration is isolated from brokerage workspaces. Authentication claims, Firestore Rules and audit logs remain the authorization boundary.</p></div></div>'
}
function fmt(v){return M(v)}
async function table(c){
 let [title,fields]=mod[c],rows=await load(c),q=(document.getElementById("search")?.value||"").toLowerCase();if(q)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q));
 return '<div class="page-head"><div><div class="eyebrow">Admin</div><h1>'+E(title)+'</h1></div><div class="actions"><button class="btn btn-primary" data-add="'+c+'">'+t("add")+'</button><button class="btn" data-csv="'+c+'">CSV</button></div></div><div class="card" style="margin-bottom:14px"><div class="field"><label>'+t("search")+'</label><input id="search"></div></div>'+(rows.length?'<div class="table-wrap"><table class="data-table"><thead><tr>'+fields.map(f=>'<th>'+E(f[1])+'</th>').join("")+'<th></th></tr></thead><tbody>'+rows.map(r=>'<tr>'+fields.map(f=>'<td>'+E(r[f[0]]==null||r[f[0]]===""?"—":r[f[0]])+'</td>').join("")+'<td><div class="actions"><button class="btn" data-edit="'+c+':'+r.id+'">'+t("edit")+'</button><button class="btn btn-danger" data-del="'+c+':'+r.id+'">'+t("delete")+'</button></div></td></tr>').join("")+'</tbody></table></div>':'<div class="card empty">'+t("empty")+'</div>')
}
async function analytics(){let p=await load("policies"),c=await load("claims"),r=await load("renewals"),cm=await load("commissions");let premium=p.reduce((n,x)=>n+Number(x.premium||0),0),commission=cm.reduce((n,x)=>n+Number(x.commissionAmount||0),0),renewal=r.length?Math.round(r.filter(x=>x.status==="Renewed").length/r.length*100):0,open=c.filter(x=>!["Settled","Closed","Rejected"].includes(x.status)).length;return '<div class="page-head"><div><div class="eyebrow">📊 Analytics</div><h1>Platform Analytics</h1></div></div><div class="stats"><div class="stat"><div class="value">'+fmt(premium)+'</div><div class="label">Premium</div></div><div class="stat"><div class="value">'+fmt(commission)+'</div><div class="label">Commission</div></div><div class="stat"><div class="value">'+renewal+'%</div><div class="label">Renewal rate</div></div><div class="stat"><div class="value">'+open+'</div><div class="label">Open claims</div></div></div>'}
async function audit(){let rows=await load("auditLogs");return '<div class="page-head"><div><div class="eyebrow">🔎 Audit</div><h1>Audit Logs</h1></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Action</th><th>Target</th><th>Actor</th><th>Workspace</th><th>Created</th></tr></thead><tbody>'+rows.map(r=>'<tr><td>'+E(r.action||"")+'</td><td>'+E((r.targetType||"")+" / "+(r.targetId||""))+'</td><td>'+E(r.actorEmail||r.actorId||"")+'</td><td>'+E(r.organizationId||"platform")+'</td><td>'+D(r.createdAt)+'</td></tr>').join("")+'</tbody></table></div>'}
function form(c,row){let fs=mod[c][1];return '<form id="adminForm" class="form-stack"><div class="form-grid">'+fs.map(f=>{let v=row[f[0]]??"";if(f[2]==="textarea")return '<div class="field" style="grid-column:1/-1"><label>'+E(f[1])+'</label><textarea name="'+f[0]+'">'+E(v)+'</textarea></div>';if(f[2]==="select")return '<div class="field"><label>'+E(f[1])+'</label><select name="'+f[0]+'">'+String(f[3]).split(",").map(x=>x=x.trim()).map(x=>'<option value="'+E(x)+'" '+(String(v)===x?"selected":"")+'>'+E(x)+'</option>').join("")+'</select></div>';return '<div class="field"><label>'+E(f[1])+'</label><input type="'+f[2]+'" name="'+f[0]+'" value="'+E(v)+'"></div>'}).join("")+'</div><div class="form-actions"><button type="button" class="btn" data-close-modal>'+t("cancel")+'</button><button class="btn btn-primary">'+t("save")+'</button></div></form>'}
function edit(c,id){let row=id?(cache[c]||[]).find(x=>x.id===id)||{}:{};document.getElementById("modalTitle").textContent=(id?t("edit"):t("add"))+" "+mod[c][0];document.getElementById("modalBody").innerHTML=form(c,row);document.getElementById("modal").classList.add("show");document.getElementById("adminForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.currentTarget),d={};mod[c][1].forEach(x=>d[x[0]]=x[2]==="number"&&f.get(x[0])!==""?Number(f.get(x[0])):f.get(x[0]));try{if(id)await db.collection(c).doc(id).update({...d,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});else{let ref=await db.collection(c).add({...d,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:S.user.uid});id=ref.id}await db.collection("auditLogs").add({action:id?"admin_save":"admin_create",targetType:c,targetId:id,actorId:S.user.uid,actorEmail:S.user.email||"",createdAt:firebase.firestore.FieldValue.serverTimestamp()});invalidate();close();toast(t("saved"));render()}catch(x){toast(err(x),"error")}}}
async function del(c,id){if(!confirm(t("delete")+"?"))return;try{await db.collection(c).doc(id).delete();await db.collection("auditLogs").add({action:"admin_delete",targetType:c,targetId:id,actorId:S.user.uid,actorEmail:S.user.email||"",createdAt:firebase.firestore.FieldValue.serverTimestamp()});invalidate();toast(t("deleted"));render()}catch(x){toast(err(x),"error")}}
function close(){document.getElementById("modal").classList.remove("show")}
async function render(){let root=document.getElementById("adminView");if(!root)return;root.innerHTML='<div class="loading">'+t("loading")+'</div>';try{root.innerHTML=view==="dashboard"?await dashboard():view==="analytics"?await analytics():view==="auditLogs"?await audit():mod[view]?await table(view):'<div class="card empty">'+t("empty")+'</div>';wire()}catch(x){root.innerHTML='<div class="error-box">'+E(err(x))+'</div>'}}
function wire(){document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>edit(b.dataset.add,null));document.querySelectorAll("[data-edit]").forEach(b=>{let p=b.dataset.edit.split(":");b.onclick=()=>edit(p[0],p[1])});document.querySelectorAll("[data-del]").forEach(b=>{let p=b.dataset.del.split(":");b.onclick=()=>del(p[0],p[1])});document.getElementById("search")?.addEventListener("input",()=>{let q=document.getElementById("search").value.toLowerCase();document.querySelectorAll(".data-table tbody tr").forEach(tr=>tr.style.display=tr.textContent.toLowerCase().includes(q)?"":"none")})}
function logout(){A.signOut().then(()=>login())}
A.onAuthStateChanged(()=>guard());window.addEventListener("hashchange",()=>{view=(location.hash||"#dashboard").slice(1);if(A.currentUser)render()});document.addEventListener("click",e=>{if(e.target.matches("[data-close-modal]")||e.target.id==="modal")close()});
})();