(function(){
  var A=InsurNex.auth,db=InsurNex.db,state=InsurNex.state,t=InsurNex.t,esc=InsurNex.esc,fmtDate=InsurNex.fmtDate,fmtMoney=InsurNex.fmtMoney,toast=InsurNex.toast,friendlyError=InsurNex.friendlyError;
  var view=(location.hash||"#dashboard").slice(1), cache={};
  var modules={
    users:{title:"Users",fields:[["name","name","text"],["email","email","email"],["mobile","mobile","tel"],["accountType","accountType","text"],["status","status","select","active,suspended"]]},
    brokerProfiles:{title:"Brokers",fields:[["userId","userId","text"],["licenseNumber","brokerLicense","text"],["companyName","companyName","text"],["status","status","select","active,suspended"]]},organizations:{title:"Organizations",fields:[["name","companyName","text"],["ownerId","ownerId","text"],["status","status","select","active,suspended"]]},
    clients:{title:"Clients",fields:[["fullName","name","text"],["type","type","select","individual,corporate"],["email","email","email"],["phone","mobile","tel"],["status","status","select","active,inactive"]]},
    leads:{title:"Leads",fields:[["fullName","name","text"],["companyName","companyName","text"],["stage","stage","select","New,Contacted,Qualified,Proposal,Negotiation,Won,Lost"],["source","source","text"],["status","status","select","open,closed"]]},
    policies:{title:"Policies",fields:[["policyNumber","policyNumber","text"],["clientName","clientName","text"],["insurer","insurer","text"],["product","product","text"],["premium","premium","number"],["expiryDate","expiryDate","date"],["status","status","select","active,expired,cancelled,pending"]]},
    quotes:{title:"Quotes",fields:[["clientName","clientName","text"],["insurer","insurer","text"],["product","product","text"],["premium","premium","number"],["status","status","select","draft,sent,accepted,rejected,expired"]]},
    renewals:{title:"Renewals",fields:[["policyNumber","policyNumber","text"],["clientName","clientName","text"],["dueDate","dueDate","date"],["status","status","select","90,60,45,30,15,7,1,renewed,lost"]]},
    claims:{title:"Claims",fields:[["policyNumber","policyNumber","text"],["clientName","clientName","text"],["amount","amount","number"],["status","status","select","New,Submitted,Under Review,Additional Documents,Approved,Rejected,Paid,Closed"],["description","description","textarea"]]},
    supportTickets:{title:"Support",fields:[["subject","subject","text"],["priority","priority","select","low,medium,high,urgent"],["status","status","select","open,inProgress,waitingUser,resolved,closed"],["message","description","textarea"]]},
    knowledgeBase:{title:"Knowledge Base",fields:[["title","subject","text"],["category","type","text"],["status","status","select","draft,published"],["body","description","textarea"]]},
    announcements:{title:"Announcements",fields:[["title","subject","text"],["type","type","text"],["status","status","select","draft,published"],["body","description","textarea"]]},
    subscriptions:{title:"Subscriptions",fields:[["userId","ownerId","text"],["plan","type","text"],["status","status","select","trial,active,pastDue,cancelled"],["renewalDate","dueDate","date"]]},
    invoices:{title:"Invoices",fields:[["customerId","ownerId","text"],["amount","amount","number"],["status","status","select","draft,open,paid,void"],["dueDate","dueDate","date"]]},
    settings:{title:"System Settings",fields:[["key","type","text"],["value","description","textarea"]]}
  };
  var nav=["dashboard","users","organizations","brokerProfiles","clients","leads","policies","quotes","renewals","claims","supportTickets","knowledgeBase","announcements","subscriptions","invoices","auditLogs","settings"];

  function mark(){return '<div class="brand-mark">IN</div>';}
  function shell(){
    var links=nav.map(function(n){return '<a class="drawer-link" href="#'+n+'" data-nav="'+n+'"><span>'+label(n)+'</span><span>›</span></a>';}).join("");
    document.getElementById("adminApp").innerHTML='<div class="app-shell"><aside class="desktop-drawer"><div class="drawer-head">'+mark()+' <strong>InsurNex Admin</strong></div>'+links+'<button class="btn btn-danger" id="logout" style="margin-top:12px">'+t("logout")+'</button></aside><main class="main"><header class="topbar"><div class="brand">'+mark()+'<div><div class="brand-name">InsurNex Admin</div><div class="subtitle">Platform management console</div></div></div><div class="actions"><button class="btn" id="lang">AR/EN</button><button class="btn" id="menu">☰</button><button class="btn" id="logout2">⇥</button></div></header><section id="adminView" class="content"></section></main><div class="drawer" id="drawer"><div class="drawer-panel"><div class="drawer-head"><strong>InsurNex Admin</strong><button class="close" id="closeDrawer">×</button></div>'+links+'<button class="btn btn-danger" id="logout3" style="margin-top:12px">'+t("logout")+'</button></div></div></div>';
    document.querySelectorAll("[data-nav]").forEach(function(b){b.onclick=function(e){e.preventDefault();view=b.dataset.nav;location.hash=view;render();document.getElementById("drawer").classList.remove("show");};});
    document.getElementById("logout").onclick=logout;document.getElementById("logout2").onclick=logout;document.getElementById("logout3").onclick=logout;
    document.getElementById("menu").onclick=function(){document.getElementById("drawer").classList.add("show");};document.getElementById("closeDrawer").onclick=function(){document.getElementById("drawer").classList.remove("show");};
    document.getElementById("lang").onclick=function(){InsurNex.setLanguage(InsurNex.locale()==="ar"?"en":"ar");shell();render();};
  }
  function label(n){return modules[n]?.title||({dashboard:"Dashboard",auditLogs:"Audit Logs"}[n]||n);}
  function login(error){
    document.getElementById("adminApp").innerHTML='<main class="auth-wrap"><div class="auth-card"><div class="auth-logo">'+mark()+'<div><div class="brand-name">InsurNex Admin</div><div class="subtitle">Restricted platform administration</div></div></div><h1 class="auth-title">'+t("login")+'</h1>'+ (error?'<div class="error-box">'+esc(error)+'</div>':'') +'<form id="adminLogin" class="form-stack"><div class="field"><label>'+t("email")+'</label><input type="email" name="email" required></div><div class="field"><label>'+t("password")+'</label><input type="password" name="password" required></div><button class="btn btn-primary">'+t("login")+'</button></form><div class="section-note" style="margin-top:12px">الوصول يتطلب Custom Claim: platformRole = superAdmin أو platformAdmin. استخدم scripts/set-admin-claims.cjs لإسناد الصلاحية من بيئة موثوقة.</div></div></main>';
    document.getElementById("adminLogin").onsubmit=async function(e){e.preventDefault();try{var f=new FormData(e.currentTarget);await A.signInWithEmailAndPassword(String(f.get("email")).trim(),String(f.get("password")));await guard();}catch(err){login(friendlyError(err));}};
  }
  async function guard(){var u=A.currentUser;if(!u){login();return;}var token=await u.getIdTokenResult(true),role=token.claims.platformRole;if(role!=="superAdmin"&&role!=="platformAdmin"){await A.signOut();login("الحساب لا يملك صلاحية InsurNex Admin.");return;}state.user=u;state.adminRole=role;shell();render();}
  async function load(c){if(c==="auditLogs"){var s=await db.collection(c).limit(100).get();cache[c]=s.docs.map(function(d){return Object.assign({id:d.id},d.data());});return cache[c];}var s=await db.collection(c).limit(100).get();cache[c]=s.docs.map(function(d){return Object.assign({id:d.id},d.data());});return cache[c];}
  async function dashboard(){
    var cs=await Promise.all(["users","organizations","policies","claims","renewals","supportTickets","subscriptions"].map(load)),users=cs[0],orgs=cs[1],policies=cs[2],claims=cs[3],renewals=cs[4],tickets=cs[5],subs=cs[6];
    return '<div class="page-head"><div><div class="eyebrow">InsurNex Admin</div><h1>Dashboard</h1><div class="muted">Role: '+esc(state.adminRole||"platformAdmin")+'</div></div><div class="actions"><button class="btn btn-accent" id="refresh">Refresh</button></div></div><div class="stats"><div class="stat"><div class="value">'+users.length+'</div><div class="label">Users</div></div><div class="stat"><div class="value">'+orgs.length+'</div><div class="label">Organizations</div></div><div class="stat"><div class="value">'+policies.length+'</div><div class="label">Policies</div></div><div class="stat"><div class="value">'+claims.length+'</div><div class="label">Claims</div></div></div><div class="grid grid-3" style="margin-top:14px"><div class="card"><div class="kpi-title">Renewals</div><div class="stat" style="margin-top:8px"><div class="value">'+renewals.length+'</div></div></div><div class="card"><div class="kpi-title">Support tickets</div><div class="stat" style="margin-top:8px"><div class="value">'+tickets.length+'</div></div></div><div class="card"><div class="kpi-title">Subscriptions</div><div class="stat" style="margin-top:8px"><div class="value">'+subs.length+'</div></div></div></div><div class="card" style="margin-top:14px"><h3>Administrative controls</h3><p class="section-note">إدارة المستخدمين والمؤسسات والمحتوى والدعم والسجلات التدقيقية من مساحة منفصلة. قواعد Firestore وClaims هي طبقة التفويض النهائية.</p></div>';
  }
  async function moduleView(c){
    var rows=await load(c),m=modules[c];if(!m)return audit();
    return '<div class="page-head"><div><div class="eyebrow">Admin</div><h1>'+m.title+'</h1></div><div class="actions"><button class="btn btn-primary" data-add="'+c+'">Add</button></div></div><div class="card"><div class="field"><label>Search</label><input id="search" placeholder="Search"></div></div><div style="height:14px"></div>'+(rows.length?'<div class="table-wrap"><table class="data-table"><thead><tr>'+m.fields.slice(0,6).map(function(f){return '<th>'+f[1]+'</th>';}).join("")+'<th></th></tr></thead><tbody>'+rows.map(function(r){return '<tr>'+m.fields.slice(0,6).map(function(f){return '<td>'+esc(r[f[0]]??"—")+'</td>';}).join("")+'<td><div class="actions"><button class="btn" data-edit="'+c+':'+r.id+'">Edit</button><button class="btn btn-danger" data-del="'+c+':'+r.id+'">Delete</button></div></td></tr>';}).join("")+'</tbody></table></div>':'<div class="card empty">'+t("empty")+'</div>');
  }
  async function audit(){var rows=await load("auditLogs");return '<div class="page-head"><div><div class="eyebrow">🔎 Audit</div><h1>Audit Logs</h1></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Action</th><th>Target</th><th>Actor</th><th>Workspace</th><th>Created</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+esc(r.action||"")+'</td><td>'+esc((r.targetType||"")+" / "+(r.targetId||""))+'</td><td>'+esc(r.actorEmail||r.actorId||"")+'</td><td>'+esc(r.organizationId||"personal")+'</td><td>'+fmtDate(r.createdAt)+'</td></tr>';}).join("")+'</tbody></table></div>';}
  function form(c,row){var m=modules[c];return '<form id="adminForm" class="form-stack"><div class="form-grid">'+m.fields.map(function(f){var key=f[0],type=f[2],opts=f[3];if(type==="textarea")return '<div class="field" style="grid-column:1/-1"><label>'+f[1]+'</label><textarea name="'+key+'">'+esc(row[key]||"")+'</textarea></div>';if(type==="select")return '<div class="field"><label>'+f[1]+'</label><select name="'+key+'">'+String(opts).split(",").map(function(v){return '<option value="'+esc(v)+'" '+(String(row[key]||"")===v?"selected":"")+'>'+v+'</option>';}).join("")+'</select></div>';return '<div class="field"><label>'+f[1]+'</label><input type="'+type+'" name="'+key+'" value="'+esc(row[key]||"")+'"></div>';}).join("")+'</div><button class="btn btn-primary">Save</button></form>';}
  async function edit(c,id){var row=id?(cache[c]||[]).find(function(x){return x.id===id;})||{}:{};modal(c,row,id);}
  function modal(c,row,id){document.getElementById("modalTitle").textContent=(id?"Edit ":"Add ")+modules[c].title;document.getElementById("modalBody").innerHTML=form(c,row);document.getElementById("modal").classList.add("show");document.getElementById("adminForm").onsubmit=async function(e){e.preventDefault();var f=new FormData(e.currentTarget),d={};modules[c].fields.forEach(function(x){d[x[0]]=f.get(x[0]);});try{if(id)await db.collection(c).doc(id).update(Object.assign({},d,{updatedAt:firebase.firestore.FieldValue.serverTimestamp()}));else await db.collection(c).add(Object.assign({},d,{createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp(),createdBy:state.user.uid}));await db.collection("auditLogs").add({action:id?"admin_update":"admin_create",targetType:c,targetId:id||"new",actorId:state.user.uid,actorEmail:state.user.email||"",createdAt:firebase.firestore.FieldValue.serverTimestamp()});document.getElementById("modal").classList.remove("show");toast("Saved");render();}catch(err){toast(friendlyError(err),"error");}};}
  async function del(c,id){if(!confirm("Delete this record?"))return;try{await db.collection(c).doc(id).delete();await db.collection("auditLogs").add({action:"admin_delete",targetType:c,targetId:id,actorId:state.user.uid,actorEmail:state.user.email||"",createdAt:firebase.firestore.FieldValue.serverTimestamp()});toast("Deleted");render();}catch(err){toast(friendlyError(err),"error");}}
  async function render(){var root=document.getElementById("adminView");root.innerHTML='<div class="loading">'+t("loading")+'</div>';try{root.innerHTML=view==="dashboard"?await dashboard():await moduleView(view);wire();}catch(e){root.innerHTML='<div class="error-box">'+esc(friendlyError(e))+'</div>';}}
  function wire(){document.querySelectorAll("[data-add]").forEach(function(b){b.onclick=function(){edit(b.dataset.add,null);};});document.querySelectorAll("[data-edit]").forEach(function(b){var p=b.dataset.edit.split(":");b.onclick=function(){edit(p[0],p[1]);};});document.querySelectorAll("[data-del]").forEach(function(b){var p=b.dataset.del.split(":");b.onclick=function(){del(p[0],p[1]);};});document.getElementById("refresh")?.addEventListener("click",render);document.getElementById("search")?.addEventListener("input",function(){var q=this.value.toLowerCase();document.querySelectorAll(".data-table tbody tr").forEach(function(tr){tr.style.display=tr.textContent.toLowerCase().indexOf(q)>=0?"":"none";});});}
  function close(){document.getElementById("modal").classList.remove("show");}
  function logout(){A.signOut().then(login);}
  document.addEventListener("click",function(e){if(e.target.matches("[data-close-modal]")||e.target.id==="modal")close();});
  A.onAuthStateChanged(function(){guard();});
  window.addEventListener("hashchange",function(){view=(location.hash||"#dashboard").slice(1);if(A.currentUser)render();});
})();