(() => {
  const firebaseConfig = window.INSURNEX_CONFIG?.firebase;
  if (!firebaseConfig?.projectId) throw new Error("InsurNex Firebase configuration is missing.");
  if (!window.firebase?.apps?.length) firebase.initializeApp(firebaseConfig);
  const auth = firebase.auth();
  const db = firebase.firestore();
  const storage = firebase.storage();

  const I18N = {
    ar:{appName:"InsurNex",tagline:"منصة تشغيل ووساطة تأمينية احترافية",home:"الرئيسية",crm:"CRM",clients:"العملاء",leads:"الفرص",policies:"الوثائق",quotes:"عروض الأسعار",renewals:"التجديدات",claims:"المطالبات",documents:"المستندات",tasks:"المهام",calendar:"التقويم",analytics:"التحليلات",support:"الدعم",account:"الحساب",notifications:"الإشعارات",login:"تسجيل الدخول",register:"إنشاء حساب",logout:"تسجيل الخروج",email:"البريد الإلكتروني",password:"كلمة المرور",name:"الاسم الكامل",mobile:"رقم الهاتف",country:"الدولة",city:"المدينة",accountType:"نوع الحساب",individualBroker:"وسيط تأمين فردي",brokerageCompany:"شركة وساطة",companyEmployee:"موظف شركة",personalWorkspace:"المساحة الشخصية",organizationWorkspace:"مساحة المؤسسة",switchWorkspace:"تبديل المساحة",save:"حفظ",cancel:"إلغاء",add:"إضافة",edit:"تعديل",delete:"حذف",search:"بحث",loading:"جاري التحميل...",empty:"لا توجد بيانات بعد",retry:"إعادة المحاولة",close:"إغلاق",dashboard:"لوحة المتابعة",total:"الإجمالي",active:"نشط",dueSoon:"يستحق قريبًا",premium:"القسط",commission:"العمولة",status:"الحالة",noPermission:"ليس لديك صلاحية للوصول إلى هذه البيانات.",saved:"تم الحفظ بنجاح.",deleted:"تم الحذف بنجاح.",network:"تعذر الاتصال بالخدمة. تحقق من الاتصال وحاول مرة أخرى.",invalidEmail:"البريد الإلكتروني غير صالح.",invalidPassword:"كلمة المرور يجب أن تكون 6 أحرف على الأقل.",passwordsMismatch:"كلمتا المرور غير متطابقتين.",accountCreated:"تم إنشاء الحساب. أكمل إعداد مساحة العمل.",resetSent:"تم إرسال رابط استعادة كلمة المرور.",confirmDelete:"هل تريد حذف هذا السجل؟",client:"عميل",individual:"فرد",corporate:"شركة",newLead:"جديد",contacted:"تم التواصل",qualified:"مؤهل",proposal:"عرض",negotiation:"تفاوض",won:"فوز",lost:"خسارة",newPolicy:"وثيقة جديدة",submitted:"مُقدمة",underReview:"قيد المراجعة",additionalDocuments:"مستندات إضافية",approved:"معتمدة",rejected:"مرفوضة",paid:"مدفوعة",closed:"مغلقة",open:"مفتوحة",inProgress:"قيد التنفيذ",waitingUser:"بانتظار المستخدم",resolved:"محلولة",noNotifications:"لا توجد إشعارات جديدة",workspaceReady:"مساحة العمل جاهزة",organizationCreated:"تم إنشاء المؤسسة وإعداد عضويتك كمالك.",onboarding:"إعداد مساحة العمل",complete:"إتمام الإعداد",next:"التالي",back:"السابق",professionalInfo:"البيانات المهنية",workspaceSetup:"اختيار مساحة العمل",brokerLicense:"رقم الترخيص",insurer:"شركة التأمين",product:"المنتج",policyNumber:"رقم الوثيقة",startDate:"تاريخ البداية",expiryDate:"تاريخ الانتهاء",clientName:"اسم العميل",stage:"المرحلة",source:"المصدر",dueDate:"تاريخ الاستحقاق",amount:"المبلغ",priority:"الأولوية",subject:"الموضوع",description:"الوصف",type:"النوع",validUntil:"صالح حتى",companyName:"اسم الشركة"},
    en:{appName:"InsurNex",tagline:"Professional insurance broker operations platform",home:"Home",crm:"CRM",clients:"Clients",leads:"Leads",policies:"Policies",quotes:"Quotes",renewals:"Renewals",claims:"Claims",documents:"Documents",tasks:"Tasks",calendar:"Calendar",analytics:"Analytics",support:"Support",account:"Account",notifications:"Notifications",login:"Sign in",register:"Create account",logout:"Sign out",email:"Email",password:"Password",name:"Full name",mobile:"Mobile",country:"Country",city:"City",accountType:"Account type",individualBroker:"Individual Broker",brokerageCompany:"Brokerage Company",companyEmployee:"Company Employee",personalWorkspace:"Personal Workspace",organizationWorkspace:"Organization Workspace",switchWorkspace:"Switch workspace",save:"Save",cancel:"Cancel",add:"Add",edit:"Edit",delete:"Delete",search:"Search",loading:"Loading...",empty:"No data yet",retry:"Retry",close:"Close",dashboard:"Dashboard",total:"Total",active:"Active",dueSoon:"Due soon",premium:"Premium",commission:"Commission",status:"Status",noPermission:"You do not have permission to access this data.",saved:"Saved successfully.",deleted:"Deleted successfully.",network:"Service unavailable. Check your connection and retry.",invalidEmail:"Invalid email address.",invalidPassword:"Password must be at least 6 characters.",passwordsMismatch:"Passwords do not match.",accountCreated:"Account created. Complete your workspace setup.",resetSent:"Password reset link sent.",confirmDelete:"Delete this record?",client:"Client",individual:"Individual",corporate:"Corporate",newLead:"New",contacted:"Contacted",qualified:"Qualified",proposal:"Proposal",negotiation:"Negotiation",won:"Won",lost:"Lost",newPolicy:"New policy",submitted:"Submitted",underReview:"Under review",additionalDocuments:"Additional documents",approved:"Approved",rejected:"Rejected",paid:"Paid",closed:"Closed",open:"Open",inProgress:"In progress",waitingUser:"Waiting for user",resolved:"Resolved",noNotifications:"No new notifications",workspaceReady:"Workspace ready",organizationCreated:"Organization created and you are the owner.",onboarding:"Workspace setup",complete:"Complete setup",next:"Next",back:"Back",professionalInfo:"Professional details",workspaceSetup:"Workspace choice",brokerLicense:"License number",insurer:"Insurer",product:"Product",policyNumber:"Policy number",startDate:"Start date",expiryDate:"Expiry date",clientName:"Client name",stage:"Stage",source:"Source",dueDate:"Due date",amount:"Amount",priority:"Priority",subject:"Subject",description:"Description",type:"Type",validUntil:"Valid until",companyName:"Company name"}
  };
  let lang=localStorage.getItem("insurnex-language")||"ar";
  const state={user:null,profile:null,memberships:[],workspace:{type:"personal",id:null,name:null},cache:new Map()};

  function setLanguage(next){lang=next==="en"?"en":"ar";localStorage.setItem("insurnex-language",lang);document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.dispatchEvent(new CustomEvent("insurnex:language",{detail:lang}));}
  function t(key){return I18N[lang]?.[key]??I18N.en[key]??key;}
  function locale(){return lang;}
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
  function fmtDate(v){if(!v)return"—";const d=v?.toDate?v.toDate():new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString(lang==="ar"?"ar-EG":"en-US",{year:"numeric",month:"short",day:"numeric"});}
  function fmtMoney(v){return new Intl.NumberFormat(lang==="ar"?"ar-EG":"en-US",{style:"currency",currency:"EGP",maximumFractionDigits:0}).format(Number(v||0));}
  function toast(message,type="success"){const host=document.querySelector("#toastHost")||document.body;const el=document.createElement("div");el.className="toast "+type;el.textContent=message;host.appendChild(el);requestAnimationFrame(()=>el.classList.add("show"));setTimeout(()=>{el.classList.remove("show");setTimeout(()=>el.remove(),250)},3200);}
  function friendlyError(err){const code=String(err?.code||"");const map={"auth/invalid-credential":"بيانات تسجيل الدخول غير صحيحة.","auth/user-not-found":"الحساب غير موجود.","auth/wrong-password":"كلمة المرور غير صحيحة.","auth/email-already-in-use":"هذا البريد مستخدم بالفعل.","auth/weak-password":t("invalidPassword"),"auth/invalid-email":t("invalidEmail"),"permission-denied":t("noPermission")};return map[code]||t("network");}
  async function loadIdentity(){const u=auth.currentUser;state.user=u;if(!u){state.profile=null;state.memberships=[];return null;}const snap=await db.collection("users").doc(u.uid).get();state.profile=snap.exists?snap.data():{};const ms=await db.collection("organizationMembers").where("userId","==",u.uid).limit(20).get();state.memberships=ms.docs.map(d=>({id:d.id,...d.data()}));const current=localStorage.getItem("insurnex-workspace");if(current){try{const p=JSON.parse(current);if(p.type==="organization"&&state.memberships.some(m=>m.organizationId===p.id))state.workspace=p;}catch{}}if(!state.workspace.id&&state.memberships.length){state.workspace={type:"organization",id:state.memberships[0].organizationId,name:state.memberships[0].organizationName||null};}else if(!state.workspace.id)state.workspace={type:"personal",id:null,name:null};return state.profile;}
  function setWorkspace(ws){state.workspace=ws;localStorage.setItem("insurnex-workspace",JSON.stringify(ws));document.dispatchEvent(new CustomEvent("insurnex:workspace",{detail:ws}));}
  function scopedQuery(name,workspace=state.workspace,limit=50){let q=db.collection(name);if(workspace.type==="organization"&&workspace.id)q=q.where("organizationId","==",workspace.id).where("workspaceType","==","organization");else q=q.where("ownerId","==",auth.currentUser.uid).where("workspaceType","==","personal");return q.limit(limit);}
  function docPayload(data={},workspace=state.workspace){const user=auth.currentUser;return{...data,workspaceType:workspace.type,organizationId:workspace.type==="organization"?workspace.id:null,ownerId:user.uid,createdBy:user.uid,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),createdAt:data.createdAt||firebase.firestore.FieldValue.serverTimestamp()};}
  async function writeAudit(action,targetType,targetId,metadata={}){const user=auth.currentUser;if(!user)return;try{await db.collection("auditLogs").add({action,targetType,targetId,actorId:user.uid,actorEmail:user.email||"",organizationId:state.workspace.type==="organization"?state.workspace.id:null,metadata,createdAt:firebase.firestore.FieldValue.serverTimestamp()});}catch(e){console.warn("audit",e);}}
  async function queryDocs(collection,workspace=state.workspace,limit=50){const snap=await scopedQuery(collection,workspace,limit).get();const rows=snap.docs.map(d=>({id:d.id,...d.data()}));rows.sort((a,b)=>{const ta=a.createdAt?.toMillis?a.createdAt.toMillis():Date.parse(a.createdAt||"");const tb=b.createdAt?.toMillis?b.createdAt.toMillis():Date.parse(b.createdAt||"");return tb-ta;});state.cache.set(collection,rows);return rows;}
  const Domain={clients:{title:"clients",icon:"👥",fields:[["fullName","name","text"],["type","type","select","individual,corporate"],["phone","mobile","tel"],["email","email","email"],["companyName","companyName","text"],["status","status","select","active,inactive"]]},leads:{title:"leads",icon:"🎯",fields:[["fullName","name","text"],["companyName","companyName","text"],["phone","mobile","tel"],["email","email","email"],["source","source","text"],["stage","stage","select","New,Contacted,Qualified,Proposal,Negotiation,Won,Lost"],["estimatedPremium","premium","number"]]},policies:{title:"policies",icon:"🛡️",fields:[["policyNumber","policyNumber","text"],["clientName","clientName","text"],["insurer","insurer","text"],["product","product","text"],["startDate","startDate","date"],["expiryDate","expiryDate","date"],["premium","premium","number"],["commission","commission","number"],["status","status","select","active,expired,cancelled,pending"]]},quotes:{title:"quotes",icon:"📑",fields:[["clientName","clientName","text"],["insurer","insurer","text"],["product","product","text"],["premium","premium","number"],["validUntil","validUntil","date"],["status","status","select","draft,sent,accepted,rejected,expired"]]},renewals:{title:"renewals",icon:"🔄",fields:[["policyNumber","policyNumber","text"],["clientName","clientName","text"],["dueDate","dueDate","date"],["status","status","select","90,60,45,30,15,7,1,renewed,lost"]]},claims:{title:"claims",icon:"🧾",fields:[["policyNumber","policyNumber","text"],["clientName","clientName","text"],["amount","amount","number"],["status","status","select","New,Submitted,Under Review,Additional Documents,Approved,Rejected,Paid,Closed"],["description","description","textarea"]]},tasks:{title:"tasks",icon:"✅",fields:[["title","subject","text"],["dueDate","dueDate","date"],["priority","priority","select","low,medium,high,urgent"],["status","status","select","open,inProgress,waitingUser,resolved,closed"],["description","description","textarea"]]},appointments:{title:"calendar",icon:"📅",fields:[["title","subject","text"],["date","dueDate","datetime-local"],["clientName","clientName","text"],["type","type","text"],["status","status","select","scheduled,completed,cancelled"]]},supportTickets:{title:"support",icon:"🎧",fields:[["subject","subject","text"],["priority","priority","select","low,medium,high,urgent"],["status","status","select","open,inProgress,waitingUser,resolved,closed"],["message","description","textarea"]]}};
  window.InsurNex={auth,db,storage,state,I18N,Domain,t,setLanguage,locale,esc,fmtDate,fmtMoney,toast,friendlyError,loadIdentity,setWorkspace,scopedQuery,docPayload,writeAudit,queryDocs};
  setLanguage(lang);
})();