(function(){
  var auth=InsurNex.auth, db=InsurNex.db, storage=InsurNex.storage, state=InsurNex.state, Domain=InsurNex.Domain;
  var t=InsurNex.t, esc=InsurNex.esc, fmtDate=InsurNex.fmtDate, fmtMoney=InsurNex.fmtMoney, toast=InsurNex.toast, friendlyError=InsurNex.friendlyError;
  var view=(location.hash||"#home").slice(1), search="";
  var nav=[["home","home","⌂"],["clients","clients","👥"],["leads","leads","🎯"],["policies","policies","🛡️"],["quotes","quotes","📑"],["renewals","renewals","🔄"],["claims","claims","🧾"],["tasks","tasks","✅"],["appointments","calendar","📅"],["analytics","analytics","📊"],["documents","documents","📎"],["supportTickets","support","🎧"],["notifications","notifications","🔔"],["account","account","⚙️"]];
  var shortNav=[["home","home","⌂"],["clients","clients","👥"],["policies","policies","🛡️"],["renewals","renewals","🔄"],["account","account","⚙️"]];

  function mark(){return '<div class="brand-mark">IN</div>';}
  function modal(title,html){document.getElementById("modalTitle").textContent=title;document.getElementById("modalBody").innerHTML=html;document.getElementById("modal").classList.add("show");}
  function closeModal(){document.getElementById("modal").classList.remove("show");}
  function navigate(v){view=v;search="";location.hash=v;render();}
  function authPage(mode,error){
    var login=mode==="login";
    document.getElementById("app").innerHTML='<main class="auth-wrap"><div class="auth-card"><div class="auth-logo">'+mark()+'<div><div class="brand-name">InsurNex</div><div class="subtitle">'+esc(t("tagline"))+'</div></div></div><h1 class="auth-title">'+(login?t("login"):t("register"))+'</h1><p class="auth-copy">إدارة العملاء والوثائق والعروض والتجديدات والمطالبات من مساحة عمل واحدة.</p>'+ (error?'<div class="error-box">'+esc(error)+'</div>':'') +'<form id="authForm" class="form-stack" style="margin-top:16px">'+(!login?'<div class="form-grid"><div class="field"><label>'+t("name")+'</label><input name="name" required></div><div class="field"><label>'+t("mobile")+'</label><input name="mobile" required></div><div class="field"><label>'+t("country")+'</label><input name="country" value="Egypt"></div><div class="field"><label>'+t("city")+'</label><input name="city"></div></div>':'')+'<div class="field"><label>'+t("email")+'</label><input type="email" name="email" required></div><div class="field"><label>'+t("password")+'</label><input type="password" name="password" minlength="6" required></div>'+(!login?'<div class="form-grid"><div class="field"><label>'+t("accountType")+'</label><select name="accountType"><option value="individualBroker">'+t("individualBroker")+'</option><option value="brokerageCompany">'+t("brokerageCompany")+'</option><option value="companyEmployee">'+t("companyEmployee")+'</option></select></div><div class="field"><label>'+t("brokerLicense")+'</label><input name="brokerLicense"></div><div class="field"><label>'+t("companyName")+'</label><input name="companyName"></div></div><label class="checkbox"><input type="checkbox" name="terms" required><span>أوافق على شروط الاستخدام وسياسة الخصوصية.</span></label>':'')+'<button class="btn btn-primary">'+(login?t("login"):t("register"))+'</button></form><div class="actions" style="margin-top:12px"><button class="btn" id="switchAuth">'+(login?t("register"):t("login"))+'</button>'+(login?'<button class="btn" id="forgot">نسيت كلمة المرور؟</button>':'')+'<button class="btn" id="lang">'+(InsurNex.locale()==="ar"?"English":"العربية")+'</button></div></div></main>';
    document.getElementById("switchAuth").onclick=function(){authPage(login?"register":"login");};
    document.getElementById("lang").onclick=function(){InsurNex.setLanguage(InsurNex.locale()==="ar"?"en":"ar");authPage(mode);};
    if(login)document.getElementById("forgot").onclick=forgot;
    document.getElementById("authForm").onsubmit=async function(e){e.preventDefault();try{var f=new FormData(e.currentTarget);if(login)await doLogin(f);else await doRegister(f);}catch(err){authPage(mode,friendlyError(err));}};
  }
  async function doLogin(f){await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.signInWithEmailAndPassword(String(f.get("email")).trim(),String(f.get("password")));if(!auth.currentUser.emailVerified){await auth.signOut();var e=new Error("email-not-verified");e.code="auth/email-not-verified";throw e;}await InsurNex.loadIdentity();await enter();}
  async function doRegister(f){
    var c=await auth.createUserWithEmailAndPassword(String(f.get("email")).trim(),String(f.get("password")));
    var uid=c.user.uid, type=String(f.get("accountType")), batch=db.batch();
    var roles=type==="brokerageCompany"?["organizationOwner","broker"]:["broker"];
    batch.set(db.collection("users").doc(uid),{uid:uid,email:c.user.email,name:String(f.get("name")||""),mobile:String(f.get("mobile")||""),country:String(f.get("country")||""),city:String(f.get("city")||""),accountType:type,roles:roles,onboardingComplete:false,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});
    batch.set(db.collection("brokerProfiles").doc(uid),{userId:uid,licenseNumber:String(f.get("brokerLicense")||""),companyName:String(f.get("companyName")||""),createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});
    if(type==="brokerageCompany"){var org=db.collection("organizations").doc(),name=String(f.get("companyName")||"InsurNex Brokerage");batch.set(org,{name:name,ownerId:uid,status:"active",country:String(f.get("country")||""),city:String(f.get("city")||""),createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});batch.set(db.collection("organizationMembers").doc(org.id+"_"+uid),{organizationId:org.id,organizationName:name,userId:uid,role:"organizationOwner",status:"active",createdAt:firebase.firestore.FieldValue.serverTimestamp()});InsurNex.setWorkspace({type:"organization",id:org.id,name:name});}
    await batch.commit();try{await c.user.sendEmailVerification();}catch(e){}await InsurNex.loadIdentity();toast(t("accountCreated"));enter();
  }
  async function forgot(){var email=prompt(t("email"));if(!email)return;await auth.sendPasswordResetEmail(email.trim());toast(t("resetSent"));}

  function shell(){
    var links=nav.map(function(n){return '<a class="drawer-link" href="#'+n[0]+'" data-nav="'+n[0]+'"><span>'+n[2]+' '+t(n[1])+'</span><span>›</span></a>';}).join("");
    var bottom=shortNav.map(function(n){return '<button data-nav="'+n[0]+'" class="'+(view===n[0]?"active":"")+'"><span class="icon">'+n[2]+'</span><span>'+t(n[1])+'</span></button>';}).join("")+'<button id="openMenu"><span class="icon">☰</span><span>Menu</span></button>';
    document.getElementById("app").innerHTML='<div class="app-shell"><aside class="desktop-drawer"><div class="drawer-head">'+mark()+' <strong>InsurNex</strong></div>'+links+'</aside><main class="main"><header class="topbar"><div class="brand">'+mark()+'<div><div class="brand-name">InsurNex</div><div class="subtitle">'+esc(state.workspace.name||t("personalWorkspace"))+'</div></div></div><div class="actions"><button class="btn" id="lang">'+(InsurNex.locale()==="ar"?"EN":"AR")+'</button><button class="btn" id="menu">☰</button><button class="btn" id="logout">⇥</button></div></header><section id="view" class="content"></section></main><nav class="bottom-nav">'+bottom+'</nav><div class="drawer" id="drawer"><div class="drawer-panel"><div class="drawer-head"><strong>InsurNex</strong><button class="close" id="closeDrawer">×</button></div>'+links+'<div class="workspace-card" style="margin-top:12px"><div>'+ (state.workspace.type==="organization"?"🏢":"👤")+'</div><div><div class="list-title">'+esc(state.workspace.name||t("personalWorkspace"))+'</div><div class="list-sub">'+esc((state.profile&&state.profile.roles||["broker"]).join(" · "))+'</div></div></div><button class="btn" id="switchWorkspace" style="margin-top:10px">'+t("switchWorkspace")+'</button></div></div></div>';
    document.querySelectorAll("[data-nav]").forEach(function(b){b.onclick=function(e){e.preventDefault();navigate(b.dataset.nav);document.getElementById("drawer").classList.remove("show");};});
    document.getElementById("menu").onclick=function(){document.getElementById("drawer").classList.add("show");};
    document.getElementById("openMenu").onclick=function(){document.getElementById("drawer").classList.add("show");};
    document.getElementById("closeDrawer").onclick=function(){document.getElementById("drawer").classList.remove("show");};
    document.getElementById("drawer").onclick=function(e){if(e.target.id==="drawer")e.currentTarget.classList.remove("show");};
    document.getElementById("logout").onclick=logout;
    document.getElementById("lang").onclick=function(){InsurNex.setLanguage(InsurNex.locale()==="ar"?"en":"ar");shell();render();};
    document.getElementById("switchWorkspace").onclick=switchWorkspace;
  }
  async function switchWorkspace(){var opts=[{type:"personal",id:null,name:t("personalWorkspace")}].concat(state.memberships.map(function(m){return{type:"organization",id:m.organizationId,name:m.organizationName||"Organization"};}));var n=prompt(opts.map(function(o,i){return(i+1)+". "+o.name;}).join("\\n"));var i=parseInt(n,10)-1;if(opts[i]){InsurNex.setWorkspace(opts[i]);shell();render();}}
  async function enter(){shell();if(!(state.profile&&state.profile.onboardingComplete))onboarding();else render();}
  function onboarding(){modal(t("onboarding"),'<form id="onboard" class="form-stack"><div class="hero"><div class="eyebrow">InsurNex</div><h2>'+t("workspaceReady")+'</h2><p>'+t("professionalInfo")+' · '+t("workspaceSetup")+'</p></div><div class="form-grid"><div class="field"><label>'+t("brokerLicense")+'</label><input name="license"></div><div class="field"><label>'+t("companyName")+'</label><input name="companyName"></div><div class="field"><label>'+t("country")+'</label><input name="country" value="'+esc(state.profile.country||"Egypt")+'"></div><div class="field"><label>'+t("city")+'</label><input name="city" value="'+esc(state.profile.city||"")+'"></div></div><button class="btn btn-primary">'+t("complete")+'</button></form>');document.getElementById("onboard").onsubmit=async function(e){e.preventDefault();var f=new FormData(e.currentTarget);try{await db.collection("users").doc(state.user.uid).update({country:f.get("country"),city:f.get("city"),onboardingComplete:true,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});await db.collection("brokerProfiles").doc(state.user.uid).set({licenseNumber:f.get("license"),companyName:f.get("companyName"),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});closeModal();await InsurNex.loadIdentity();render();toast(t("saved"));}catch(err){toast(friendlyError(err),"error");}};}
  function closeModal(){document.getElementById("modal").classList.remove("show");}
  document.addEventListener("click",function(e){if(e.target.matches("[data-close-modal]")||e.target.id==="modal")closeModal();});

  async function render(){
    var root=document.getElementById("view");root.innerHTML='<div class="loading">'+t("loading")+'</div>';
    try{if(view==="home")root.innerHTML=await home();else if(view==="analytics")root.innerHTML=await analytics();else if(view==="account")root.innerHTML=account();else if(view==="documents")root.innerHTML=await documents();else if(view==="notifications")root.innerHTML=await notifications();else root.innerHTML=await records(view);wire();}catch(err){root.innerHTML='<div class="error-box">'+esc(friendlyError(err))+'<div style="margin-top:8px"><button class="btn" id="retry">'+t("retry")+'</button></div></div>';document.getElementById("retry").onclick=render;}}
  async function home(){
    var all=await Promise.all(["clients","leads","policies","renewals","claims","tasks"].map(function(c){return InsurNex.queryDocs(c);})),clients=all[0],leads=all[1],policies=all[2],renewals=all[3],claims=all[4],tasks=all[5];
    var exp=policies.filter(function(p){return p.expiryDate&&new Date(p.expiryDate)>=new Date()&&new Date(p.expiryDate)-Date.now()<45*86400000;}).length;
    var prem=policies.reduce(function(n,p){return n+Number(p.premium||0);},0),comm=policies.reduce(function(n,p){return n+Number(p.commission||0);},0);
    return '<div class="page-head"><div><div class="eyebrow">InsurNex</div><h1>'+t("dashboard")+'</h1><div class="muted">'+esc(state.profile&&state.profile.name||state.user.email)+'</div></div><div class="actions"><button class="btn btn-accent" data-add="clients">'+t("add")+" "+t("clients")+'</button></div></div><div class="hero" style="margin-bottom:14px"><div class="eyebrow">'+(state.workspace.type==="organization"?t("organizationWorkspace"):t("personalWorkspace"))+'</div><h2>'+esc(state.workspace.name||t("personalWorkspace"))+'</h2><p>'+t("tagline")+'</p></div><div class="stats"><div class="stat"><div class="value">'+clients.length+'</div><div class="label">'+t("clients")+'</div></div><div class="stat"><div class="value">'+leads.length+'</div><div class="label">'+t("leads")+'</div></div><div class="stat"><div class="value">'+policies.length+'</div><div class="label">'+t("policies")+'</div></div><div class="stat"><div class="value">'+exp+'</div><div class="label">'+t("dueSoon")+'</div></div></div><div class="grid grid-2" style="margin-top:14px"><div class="card"><h3>'+t("premium")+' / '+t("commission")+'</h3><div class="list"><div class="list-row"><span>'+t("premium")+'</span><strong>'+fmtMoney(prem)+'</strong></div><div class="list-row"><span>'+t("commission")+'</span><strong>'+fmtMoney(comm)+'</strong></div></div></div><div class="card"><h3>'+t("tasks")+'</h3>'+taskList(tasks)+'</div></div><div class="grid grid-3" style="margin-top:14px"><div class="card"><div class="kpi-title">'+t("renewals")+'</div><div class="stat" style="margin-top:8px"><div class="value">'+renewals.length+'</div></div></div><div class="card"><div class="kpi-title">'+t("claims")+'</div><div class="stat" style="margin-top:8px"><div class="value">'+claims.length+'</div></div></div><div class="card"><div class="kpi-title">'+t("leads")+'</div><div class="stat" style="margin-top:8px"><div class="value">'+leads.filter(function(l){return l.stage==="Won";}).length+'</div></div></div></div>';
  }
  function taskList(rows){if(!rows.length)return '<div class="empty"><div class="emoji">✅</div>'+t("empty")+'</div>';return '<div class="list">'+rows.slice(0,6).map(function(r){return '<div class="list-row"><div class="list-main"><div class="list-title">'+esc(r.title||r.subject||"Task")+'</div><div class="list-sub">'+fmtDate(r.dueDate)+' · '+esc(r.status||"")+'</div></div><span class="badge">'+esc(r.priority||"medium")+'</span></div>';}).join("")+'</div>';}
  async function records(collection){
    var def=Domain[collection];if(!def)collection="clients",def=Domain.clients;
    var rows=await InsurNex.queryDocs(collection);var q=search.toLowerCase();rows=rows.filter(function(r){return !q||Object.keys(r).some(function(k){return String(r[k]||"").toLowerCase().indexOf(q)>=0;});});
    var heads=def.fields.slice(0,6).map(function(f){return '<th>'+t(f[1])+'</th>';}).join("");
    var body=rows.map(function(r){return '<tr>'+def.fields.slice(0,6).map(function(f){return '<td>'+esc(r[f[0]]||"—")+'</td>';}).join("")+'<td><span class="badge '+(["active","Won","approved","Paid","resolved"].indexOf(r.status)>=0?"success":"")+'">'+esc(r.status||"—")+'</span></td><td><div class="actions"><button class="btn" data-edit="'+collection+':'+r.id+'">'+t("edit")+'</button><button class="btn btn-danger" data-del="'+collection+':'+r.id+'">'+t("delete")+'</button></div></td></tr>';}).join("");
    return '<div class="page-head"><div><div class="eyebrow">'+def.icon+' '+t(def.title)+'</div><h1>'+t(def.title)+'</h1></div><div class="actions"><button class="btn btn-primary" data-add="'+collection+'">'+t("add")+'</button><button class="btn" data-csv="'+collection+'">CSV</button></div></div><div class="card" style="margin-bottom:14px"><div class="field"><label>'+t("search")+'</label><input id="search" value="'+esc(search)+'"></div></div>'+(rows.length?'<div class="table-wrap"><table class="data-table"><thead><tr>'+heads+'<th>'+t("status")+'</th><th></th></tr></thead><tbody>'+body+'</tbody></table></div>':'<div class="card empty"><div class="emoji">'+def.icon+'</div>'+t("empty")+'</div>');
  }
  function formHtml(c,row){var def=Domain[c];return '<form id="recordForm" class="form-stack"><div class="form-grid">'+def.fields.map(function(f){var key=f[0],lab=f[1],type=f[2],opts=f[3];if(type==="textarea")return '<div class="field" style="grid-column:1/-1"><label>'+t(lab)+'</label><textarea name="'+key+'">'+esc(row[key]||"")+'</textarea></div>';if(type==="select")return '<div class="field"><label>'+t(lab)+'</label><select name="'+key+'">'+String(opts).split(",").map(function(o){return '<option value="'+esc(o)+'" '+(String(row[key]||"")===o?"selected":"")+'>'+esc(o)+'</option>';}).join("")+'</select></div>';return '<div class="field"><label>'+t(lab)+'</label><input type="'+type+'" name="'+key+'" value="'+esc(row[key]||"")+'"></div>';}).join("")+'</div><div class="form-actions"><button type="button" class="btn" data-close-modal>'+t("cancel")+'</button><button class="btn btn-primary">'+t("save")+'</button></div></form>';}
  async function edit(c,id){var row={};if(id){row=state.cache.get(c).find(function(x){return x.id===id;})||{};}modal(id?t("edit"):t("add"),formHtml(c,row));document.getElementById("recordForm").onsubmit=async function(e){e.preventDefault();var f=new FormData(e.currentTarget),d={};Domain[c].fields.forEach(function(x){d[x[0]]=f.get(x[0]);});try{if(id)await db.collection(c).doc(id).update(Object.assign({},d,{updatedAt:firebase.firestore.FieldValue.serverTimestamp()}));else{var ref=await db.collection(c).add(InsurNex.docPayload(d));await InsurNex.writeAudit("create",c,ref.id);}closeModal();toast(t("saved"));render();}catch(err){toast(friendlyError(err),"error");}};}
  async function del(c,id){if(!confirm(t("confirmDelete")))return;try{await db.collection(c).doc(id).delete();await InsurNex.writeAudit("delete",c,id);toast(t("deleted"));render();}catch(err){toast(friendlyError(err),"error");}}
  async function documents(){var rows=await InsurNex.queryDocs("documents");return '<div class="page-head"><div><div class="eyebrow">📎 '+t("documents")+'</div><h1>'+t("documents")+'</h1></div><button class="btn btn-primary" id="upload">'+t("add")+'</button></div>'+(rows.length?'<div class="grid grid-2">'+rows.map(function(r){return '<div class="card"><div class="list-title">'+esc(r.name||r.fileName||"Document")+'</div><div class="list-sub">'+esc(r.fileName||"")+' · '+esc(r.clientName||"")+'</div><div class="actions" style="margin-top:10px"><a class="btn" href="'+esc(r.url||"#")+'" target="_blank">Open</a></div></div>';}).join("")+'</div>':'<div class="card empty">📎<br>'+t("empty")+'</div>');}
  async function upload(){modal(t("documents"),'<form id="docForm" class="form-stack"><div class="form-grid"><div class="field"><label>'+t("name")+'</label><input name="name" required></div><div class="field"><label>File</label><input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx" required></div><div class="field"><label>'+t("clientName")+'</label><input name="clientName"></div><div class="field"><label>'+t("policyNumber")+'</label><input name="policyNumber"></div></div><div class="form-actions"><button class="btn btn-primary">'+t("save")+'</button></div></form>');document.getElementById("docForm").onsubmit=async function(e){e.preventDefault();var f=new FormData(e.currentTarget),file=f.get("file");try{var safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path="documents/"+(state.workspace.id||state.user.uid)+"/"+Date.now()+"_"+safe,ref=storage.ref(path);await ref.put(file);var url=await ref.getDownloadURL(),d=InsurNex.docPayload({name:f.get("name"),clientName:f.get("clientName"),policyNumber:f.get("policyNumber"),fileName:file.name,fileType:file.type,size:file.size,storagePath:path,url:url});var snap=await db.collection("documents").add(d);await InsurNex.writeAudit("create","documents",snap.id);closeModal();toast(t("saved"));render();}catch(err){toast(friendlyError(err),"error");}};}
  async function notifications(){var s=await db.collection("notifications").where("recipientId","==",state.user.uid).limit(50).get(),rows=s.docs.map(function(d){return Object.assign({id:d.id},d.data());});return '<div class="page-head"><div><div class="eyebrow">🔔 '+t("notifications")+'</div><h1>'+t("notifications")+'</h1></div></div><div class="card">'+(rows.length?'<div class="list">'+rows.map(function(r){return '<div class="list-row"><div class="list-main"><div class="list-title">'+esc(r.title||"Notification")+'</div><div class="list-sub">'+esc(r.body||"")+'</div></div><span class="badge '+(r.read?"":"warn")+'">'+(r.read?"✓":"new")+'</span></div>';}).join("")+'</div>':'<div class="empty">🔔<br>'+t("noNotifications")+'</div>')+'</div>';}
  async function analytics(){var a=await Promise.all(["leads","policies","claims","renewals"].map(function(c){return InsurNex.queryDocs(c);})),leads=a[0],policies=a[1],claims=a[2],renewals=a[3],prem=policies.reduce(function(n,p){return n+Number(p.premium||0);},0),comm=policies.reduce(function(n,p){return n+Number(p.commission||0);},0);return '<div class="page-head"><div><div class="eyebrow">📊 '+t("analytics")+'</div><h1>'+t("analytics")+'</h1></div></div><div class="stats"><div class="stat"><div class="value">'+(leads.length?Math.round(leads.filter(function(x){return x.stage==="Won";}).length/leads.length*100):0)+'%</div><div class="label">Conversion</div></div><div class="stat"><div class="value">'+policies.length+'</div><div class="label">'+t("policies")+'</div></div><div class="stat"><div class="value">'+fmtMoney(prem)+'</div><div class="label">'+t("premium")+'</div></div><div class="stat"><div class="value">'+fmtMoney(comm)+'</div><div class="label">'+t("commission")+'</div></div></div><div class="grid grid-2" style="margin-top:14px"><div class="card"><h3>Lead pipeline</h3><div class="list">New · '+leads.filter(function(x){return x.stage==="New";}).length+'<br>Qualified · '+leads.filter(function(x){return x.stage==="Qualified";}).length+'<br>Won · '+leads.filter(function(x){return x.stage==="Won";}).length+'</div></div><div class="card"><h3>Operations</h3><div class="list"><div class="list-row"><span>'+t("renewals")+'</span><strong>'+renewals.length+'</strong></div><div class="list-row"><span>'+t("claims")+'</span><strong>'+claims.length+'</strong></div><div class="list-row"><span>Open claim amount</span><strong>'+fmtMoney(claims.filter(function(x){return ["Paid","Closed","Rejected"].indexOf(x.status)<0;}).reduce(function(n,x){return n+Number(x.amount||0);},0))+'</strong></div></div></div></div>';}
  function account(){return '<div class="page-head"><div><div class="eyebrow">⚙️ '+t("account")+'</div><h1>'+t("account")+'</h1></div></div><div class="grid grid-2"><div class="card"><h3>'+esc(state.profile&&state.profile.name||"")+'</h3><div class="muted">'+esc(state.user.email)+'</div><div class="list" style="margin-top:12px"><div class="list-row"><span>'+t("mobile")+'</span><strong>'+esc(state.profile&&state.profile.mobile||"—")+'</strong></div><div class="list-row"><span>'+t("accountType")+'</span><strong>'+esc(state.profile&&state.profile.accountType||"broker")+'</strong></div><div class="list-row"><span>Roles</span><strong>'+esc((state.profile&&state.profile.roles||[]).join(" · "))+'</strong></div></div><button class="btn btn-primary" id="profile" style="margin-top:12px">'+t("edit")+'</button></div><div class="card"><h3>'+t("switchWorkspace")+'</h3><div class="list">'+([{type:"personal",id:null,name:t("personalWorkspace")}].concat(state.memberships.map(function(m){return{type:"organization",id:m.organizationId,name:m.organizationName||"Organization"};}))).map(function(w){return '<div class="list-row"><div class="list-title">'+esc(w.name)+'</div><button class="btn" data-workspace=\''+JSON.stringify(w)+'\'>'+(state.workspace.type===w.type&&state.workspace.id===w.id?"✓":t("switchWorkspace"))+'</button></div>';}).join("")+'</div></div></div>';}
  function profile(){var p=state.profile||{};modal(t("account"),'<form id="profileForm" class="form-stack"><div class="form-grid"><div class="field"><label>'+t("name")+'</label><input name="name" value="'+esc(p.name||"")+'"></div><div class="field"><label>'+t("mobile")+'</label><input name="mobile" value="'+esc(p.mobile||"")+'"></div><div class="field"><label>'+t("country")+'</label><input name="country" value="'+esc(p.country||"")+'"></div><div class="field"><label>'+t("city")+'</label><input name="city" value="'+esc(p.city||"")+'"></div></div><button class="btn btn-primary">'+t("save")+'</button></form>');document.getElementById("profileForm").onsubmit=async function(e){e.preventDefault();await db.collection("users").doc(state.user.uid).update(Object.assign({},Object.fromEntries(new FormData(e.currentTarget)),{updatedAt:firebase.firestore.FieldValue.serverTimestamp()}));await InsurNex.loadIdentity();closeModal();shell();render();toast(t("saved"));};}
  function wire(){var s=document.getElementById("search");if(s){s.oninput=function(){search=this.value;render();};}document.querySelectorAll("[data-add]").forEach(function(b){b.onclick=function(){edit(b.dataset.add,null);};});document.querySelectorAll("[data-edit]").forEach(function(b){var p=b.dataset.edit.split(":");b.onclick=function(){edit(p[0],p[1]);};});document.querySelectorAll("[data-del]").forEach(function(b){var p=b.dataset.del.split(":");b.onclick=function(){del(p[0],p[1]);};});document.getElementById("upload")?.addEventListener("click",upload);document.getElementById("profile")?.addEventListener("click",profile);document.querySelectorAll("[data-workspace]").forEach(function(b){b.onclick=function(){InsurNex.setWorkspace(JSON.parse(b.dataset.workspace));shell();render();};});}
  async function logout(){await auth.signOut();location.hash="";authPage("login");}
  if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js").catch(function(e){console.warn("InsurNex service worker unavailable",e);});}
  auth.onAuthStateChanged(async function(user){try{if(!user){authPage("login");return;}await InsurNex.loadIdentity();enter();}catch(e){console.error(e);authPage("login",friendlyError(e));}});
  window.addEventListener("hashchange",function(){view=(location.hash||"#home").slice(1);if(state.user){shell();render();}});
  document.addEventListener("insurnex:language",function(){if(state.user){shell();render();}});
})();