import type { ParsedTabularFile } from './file-parser.service';
export type FieldKey='writtenPremium'|'earnedPremium'|'claimAmount'|'paidAmount'|'outstanding'|'incurred'|'insuranceType'|'category'|'provider'|'member'|'claimDate';
export type MappingItem={field:FieldKey;label:string;column:string;confidence:number};
export type MappingPreview={sheet:string;columns:string[];rows:Record<string,unknown>[];mapping:MappingItem[]};
const specs:{field:FieldKey;label:string;aliases:string[]}[]=[
{field:'writtenPremium',label:'الأقساط المكتوبة',aliases:['premium','written premium','gross premium','gwp','القسط','الأقساط']},{field:'earnedPremium',label:'الأقساط المكتسبة',aliases:['earned premium','earnedpremium','ep','القسط المكتسب']},{field:'claimAmount',label:'قيمة المطالبة',aliases:['claim amount','claimed amount','claim value','قيمة المطالبة']},{field:'paidAmount',label:'المطالبات المدفوعة',aliases:['paid amount','paid claims','net paid','paid','المدفوع']},{field:'outstanding',label:'Outstanding / Reserve',aliases:['outstanding','os','os reserve','reserve','احتياطي']},{field:'incurred',label:'Incurred Claims',aliases:['incurred','incurred claims','total incurred']},{field:'insuranceType',label:'نوع التأمين',aliases:['insurance type','line','lob','line of business','نوع التأمين']},{field:'category',label:'التصنيف الطبي / Benefit',aliases:['category','service category','benefit','benefit type','medical category','التصنيف']},{field:'provider',label:'مقدم الخدمة',aliases:['provider','provider name','hospital','clinic','مقدم الخدمة']},{field:'member',label:'Member / Employee',aliases:['member','member id','employee','employee id','beneficiary','المؤمن عليه']},{field:'claimDate',label:'تاريخ المطالبة / الخدمة',aliases:['claim date','service date','date of service','dos','تاريخ المطالبة','تاريخ الخدمة']}];
const norm=(x:string)=>x.toLowerCase().replace(/[_./-]/g,' ').replace(/\s+/g,' ').trim();
function score(c0:string,aliases:string[]){const c=norm(c0);let best=0;for(const a0 of aliases){const a=norm(a0);if(c===a)best=Math.max(best,100);else if(c.includes(a)||a.includes(c))best=Math.max(best,86);else{const cw=new Set(c.split(' '));const aw=a.split(' ');const hit=aw.filter(x=>cw.has(x)).length;if(hit)best=Math.max(best,Math.round(hit/Math.max(cw.size,aw.length)*75));}}return best;}
export function buildMappingPreview(parsed:ParsedTabularFile):MappingPreview[]{return parsed.sheets.map(s=>{const columns=Array.from(new Set(s.rows.slice(0,30).flatMap(r=>Object.keys(r))));const mapping=specs.map(spec=>{let column='',confidence=0;for(const c of columns){const v=score(c,spec.aliases);if(v>confidence){column=c;confidence=v}}if(confidence<45){column='';confidence=0}return{field:spec.field,label:spec.label,column,confidence};});return{sheet:s.name,columns,rows:s.rows.slice(0,8),mapping};});}
export function mappingQuality(items:MappingItem[]){const active=items.filter(x=>x.column);return active.length?Math.round(active.reduce((a,x)=>a+x.confidence,0)/active.length):0;}
