import Anthropic from '@anthropic-ai/sdk';
import { onCall,HttpsError } from 'firebase-functions/v2/https';
import { defineSecret,defineString } from 'firebase-functions/params';
import { initializeApp } from 'firebase-admin/app';
initializeApp();
const ANTHROPIC_API_KEY=defineSecret('ANTHROPIC_API_KEY');
const CLAUDE_MODEL=defineString('CLAUDE_MEDICAL_MODEL',{default:'claude-haiku-4-5'});
type Metric={name:string;amount:number;share:number};type Signal={level:string;title:string;finding:string;evidence:string[];action:string};
interface MedicalContext{language:'ar'|'en';records:number;members:number;providers:number;gross:number;copay:number;net:number;copayRate:number;avgTransaction:number;avgMember:number;top10Share:number;top50Share:number;above50k:number;above100k:number;costDrivers:Metric[];providersRanked:Array<{name:string;count:number;members:number;gross:number;share:number;severity:number}>;membersRanked:Array<{name:string;count:number;gross:number;share:number;severity:number}>;activities:Array<{name:string;count:number;gross:number;share:number;severity:number}>;trend:Array<{month:string;count:number;members:number;gross:number;severity:number;partial:boolean}>;signals:Signal[];dataGaps:string[]}
const finite=(n:unknown)=>typeof n==='number'&&Number.isFinite(n);function valid(x:MedicalContext){return x&&['ar','en'].includes(x.language)&&finite(x.records)&&finite(x.gross)&&Array.isArray(x.costDrivers)&&x.costDrivers.length<=12&&x.providersRanked.length<=12&&x.membersRanked.length<=12&&x.activities.length<=15&&x.trend.length<=36}
const schema={type:'object',properties:{executiveSummary:{type:'string'},keyFindings:{type:'array',items:{type:'string'}},costDrivers:{type:'array',items:{type:'string'}},memberInsights:{type:'array',items:{type:'string'}},providerInsights:{type:'array',items:{type:'string'}},trendInsights:{type:'array',items:{type:'string'}},riskSignals:{type:'array',items:{type:'string'}},caseManagementOpportunities:{type:'array',items:{type:'string'}},renewalConsiderations:{type:'array',items:{type:'string'}},recommendedActions:{type:'array',items:{type:'string'}},dataLimitations:{type:'array',items:{type:'string'}}},required:['executiveSummary','keyFindings','costDrivers','memberInsights','providerInsights','trendInsights','riskSignals','caseManagementOpportunities','renewalConsiderations','recommendedActions','dataLimitations'],additionalProperties:false};
export const medicalClaudeAnalysis=onCall({region:'europe-west1',secrets:[ANTHROPIC_API_KEY],enforceAppCheck:true,timeoutSeconds:60,memory:'512MiB',maxInstances:5},async(req)=>{if(!req.auth)throw new HttpsError('unauthenticated','Authentication required.');const ctx=req.data?.context as MedicalContext;if(!valid(ctx))throw new HttpsError('invalid-argument','Invalid or oversized medical analytics context.');const client=new Anthropic({apiKey:ANTHROPIC_API_KEY.value(),timeout:45000,maxRetries:2});const language=ctx.language==='ar'?'Arabic':'English';const payload=JSON.stringify(ctx);try{const message=await client.messages.create({model:CLAUDE_MODEL.value(),max_tokens:2200,temperature:0.2,system:`You are InsurNex Medical Insurance Intelligence. Analyze insurance utilization and portfolio cost only. Never diagnose, recommend treatment, or infer missing facts. Treat all numeric metrics in the supplied JSON as authoritative deterministic calculations. Clearly distinguish evidence from interpretation. Respond in ${language}. Return only JSON matching this schema: ${JSON.stringify(schema)}`,messages:[{role:'user',content:`Analyze this aggregated medical insurance context. Do not recalculate or invent values. Context: ${payload}`}]});const text=message.content.filter(x=>x.type==='text').map(x=>x.text).join('').trim().replace(/^```json\s*/,'').replace(/```$/,'').trim();let analysis:unknown;try{analysis=JSON.parse(text)}catch{throw new HttpsError('internal','Claude returned invalid structured output.');}return{analysis,usage:message.usage,model:message.model};}catch(e){if(e instanceof HttpsError)throw e;console.error('medicalClaudeAnalysis failed',e);throw new HttpsError('unavailable','AI analysis is temporarily unavailable. Deterministic analytics remain available.')}});
