import { useEffect,useState } from 'react';
import { Bell,ClipboardCheck,ListTodo,Plus,RefreshCcw,ShieldCheck,Users,ArrowLeft,Building2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../features/auth/auth-context';
import { loadDashboard,type DashboardData } from '../features/dashboard/dashboard.service';
const empty:DashboardData={clients:0,activePolicies:0,openClaims:0,renewals:[],tasks:[],notificationCount:0};
const priority:Record<string,string>={low:'منخفضة',medium:'متوسطة',high:'مرتفعة',urgent:'عاجلة'};
export default function DashboardPage(){const {profile}=useAuth();const [data,setData]=useState(empty);const [loading,setLoading]=useState(true);useEffect(()=>{if(!profile)return;loadDashboard(profile.organizationId).then(setData).finally(()=>setLoading(false))},[profile]);return <main className="s82-home" dir="rtl">
<section className="s82-welcome"><div><span className="eyebrow">InsurNex Workspace</span><h1>مرحبًا، {profile?.displayName?.split(' ')[0]||'بك'}</h1><p>إدارة أعمال الوساطة اليومية من مكان واحد.</p></div><Link className="s82-notify" to="/notifications"><Bell size={20}/>{data.notificationCount>0&&<b>{Math.min(data.notificationCount,99)}</b>}</Link></section>
<section className="s82-section"><div className="s82-section-head"><h2>الخدمات</h2></div><div className="s82-services"><Link to="/clients"><span><Users/></span><b>العملاء</b><small>CRM</small></Link><Link to="/policies"><span><ShieldCheck/></span><b>الوثائق</b><small>Policies</small></Link><Link to="/renewals"><span><RefreshCcw/></span><b>التجديدات</b><small>Renewals</small></Link><Link to="/claims"><span><ClipboardCheck/></span><b>المطالبات</b><small>Claims</small></Link><Link to="/tasks"><span><ListTodo/></span><b>المهام</b><small>Tasks</small></Link><Link to="/insurers"><span><Building2/></span><b>الشركات</b><small>Insurers</small></Link></div></section>
<section className="s82-portfolio"><header><div><span>محفظتك اليوم</span><small>{loading?'جارٍ التحديث...':'بيانات فعلية من مساحة العمل'}</small></div><Link to="/policies">عرض المحفظة <ArrowLeft size={15}/></Link></header><div className="s82-metrics"><article><small>وثائق نشطة</small><b>{data.activePolicies}</b></article><article><small>العملاء</small><b>{data.clients}</b></article><article><small>تجديدات قريبة</small><b>{data.renewals.length}</b></article><article><small>مطالبات مفتوحة</small><b>{data.openClaims}</b></article></div><div className="s82-progress"><span style={{width:`${Math.min(100,Math.max(12,data.activePolicies*5))}%`}}/></div></section>
<section className="s82-section"><div className="s82-section-head"><h2>إجراءات سريعة</h2></div><div className="s82-quick"><Link to="/clients"><Plus/>عميل</Link><Link to="/policies"><Plus/>وثيقة</Link><Link to="/claims"><Plus/>مطالبة</Link><Link to="/tasks"><Plus/>مهمة</Link></div></section>
<section className="s82-section"><div className="s82-section-head"><h2>مهامي القادمة</h2><Link to="/tasks">عرض الكل <ArrowLeft size={14}/></Link></div><div className="s82-feed">{data.tasks.map(t=><Link key={t.id} to="/tasks"><span className={`s82-feed-icon priority-${t.priority}`}><ListTodo/></span><span><b>{t.title}</b><small>{t.dueDate||'بدون تاريخ'} · {priority[t.priority]}</small></span></Link>)}{!loading&&data.tasks.length===0&&<div className="s82-empty">لا توجد مهام مفتوحة.</div>}</div></section>
<section className="s82-section s82-last"><div className="s82-section-head"><h2>أقرب التجديدات</h2><Link to="/renewals">عرض الكل <ArrowLeft size={14}/></Link></div><div className="s82-feed">{data.renewals.map(r=><Link key={r.id} to="/renewals"><span className={`s82-feed-icon ${r.daysLeft<=7?'urgent':''}`}><RefreshCcw/></span><span><b>{r.clientName}</b><small>{r.policyNumber} · {r.daysLeft<0?'منتهية':`متبقي ${r.daysLeft} يوم`}</small></span></Link>)}{!loading&&data.renewals.length===0&&<div className="s82-empty">لا توجد تجديدات قريبة.</div>}</div></section>
</main>}
