import { ArrowRight, CheckCircle2, Save, Target, XCircle } from 'lucide-react';
import { useEffect,useMemo,useState,type FormEvent } from 'react';
import { Link,useNavigate,useParams } from 'react-router-dom';
import { useAuth } from '../features/auth/auth-context';
import { createTask } from '../features/tasks/task.service';
import { convertWonLeadToClient,getAllowedLeadStages,getLead,listLeadActivities,recordLeadTaskActivity,setLeadStage,updateLeadNotes,type LeadActivity } from '../features/leads/lead.service';
import type { Lead,LeadStage } from '../types/lead';
import { LEAD_PRIORITY_LABELS,LEAD_SOURCE_LABELS,LEAD_STAGE_LABELS } from '../types/lead';

export default function LeadDetailsPage(){
 const {id}=useParams<{id:string}>(); const nav=useNavigate(); const {user,profile}=useAuth(); const [lead,setLead]=useState<Lead|null>(null); const [acts,setActs]=useState<LeadActivity[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [notes,setNotes]=useState(''); const [lostReason,setLostReason]=useState(''); const [taskTitle,setTaskTitle]=useState(''); const [taskDue,setTaskDue]=useState('');
 async function load(){if(!id||!profile?.organizationId){setLoading(false);return;}try{setLoading(true);setError('');const [l,a]=await Promise.all([getLead(id,profile.organizationId),listLeadActivities(profile.organizationId,id)]);setLead(l);setActs(a);if(l){setNotes(l.notes||'');setLostReason(l.lostReason||'');}}catch(e){console.error(e);setError('ØªØ¹Ø°Ø± ØªØ­Ù…ÙŠÙ„ Lead 360.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[id,profile?.organizationId]); const allowed=useMemo(()=>lead?getAllowedLeadStages(lead.stage):[],[lead]);
 async function move(next:LeadStage){if(!lead||!profile||!user)return;if(next==='lost'&&!lostReason.trim()){setError('ÙŠØ±Ø¬Ù‰ ØªØ³Ø¬ÙŠÙ„ Ø³Ø¨Ø¨ ÙÙ‚Ø¯Ø§Ù† Ø§Ù„ÙØ±ØµØ©.');return;}try{setSaving(true);setError('');await setLeadStage(lead.id,lead.stage,next,profile.organizationId,user.uid,next==='lost'?lostReason:undefined);await load();}catch(e){console.error(e);setError('ØªØ¹Ø°Ø± ØªØºÙŠÙŠØ± Ø§Ù„Ù…Ø±Ø­Ù„Ø©.');}finally{setSaving(false);}}
 async function saveNotes(){if(!lead||!profile||!user)return;try{setSaving(true);await updateLeadNotes(lead.id,notes,profile.organizationId,user.uid);await load();}catch(e){console.error(e);setError('ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„Ù…Ù„Ø§Ø­Ø¸Ø§Øª.');}finally{setSaving(false);}}
 async function addTask(e:FormEvent){e.preventDefault();if(!lead||!profile||!user||!taskTitle.trim()||!taskDue)return;try{setSaving(true);await createTask({title:taskTitle.trim(),description:`Ù…ØªØ§Ø¨Ø¹Ø© ÙØ±ØµØ© Ø§Ù„Ø¨ÙŠØ¹: ${lead.name}`,priority:'medium',status:'open',dueDate:taskDue,assignedTo:user.uid,relatedType:'lead',relatedId:lead.id},profile.organizationId,user.uid);await recordLeadTaskActivity(profile.organizationId,lead.id,user.uid,taskTitle.trim());setTaskTitle('');setTaskDue('');await load();}catch(err){console.error(err);setError('ØªØ¹Ø°Ø± Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ù…Ù‡Ù…Ø©.');}finally{setSaving(false);}}
 async function convert(){if(!lead||!profile||!user)return;try{setSaving(true);setError('');const clientId=await convertWonLeadToClient(lead.id,profile.organizationId,user.uid);nav(`/clients/${clientId}`);}catch(e){console.error(e);setError('ØªØ¹Ø°Ø± ØªØ­ÙˆÙŠÙ„ Ø§Ù„ÙØ±ØµØ© Ø¥Ù„Ù‰ Ø¹Ù…ÙŠÙ„.');}finally{setSaving(false);}}
 if(loading)return <div dir="rtl">Ø¬Ø§Ø±Ù ØªØ­Ù…ÙŠÙ„ Lead 360...</div>; if(!lead)return <section className="card" dir="rtl"><h2>Ø§Ù„Ø¹Ù…ÙŠÙ„ Ø§Ù„Ù…Ø­ØªÙ…Ù„ ØºÙŠØ± Ù…ÙˆØ¬ÙˆØ¯</h2><p>{error}</p><Link to="/leads">Ø§Ù„Ø¹ÙˆØ¯Ø© Ù„Ù„Ù…Ø¨ÙŠØ¹Ø§Øª</Link></section>;
 return <div dir="rtl" style={{display:'grid',gap:16}}>
  <section className="page-header"><div><Link to="/leads"><ArrowRight size={18}/> Ø§Ù„Ù…Ø¨ÙŠØ¹Ø§Øª</Link><h1><Target size={22}/> {lead.name}</h1><p>{LEAD_STAGE_LABELS[lead.stage]} Â· {LEAD_PRIORITY_LABELS[lead.priority]}</p></div></section>
  {error&&<div className="error-message">{error}</div>}
  <section className="card"><h2>Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„ÙØ±ØµØ©</h2><p><strong>Ø§Ù„ØªØ£Ù…ÙŠÙ†:</strong> {lead.insuranceType}</p><p><strong>Ø§Ù„Ù…ØµØ¯Ø±:</strong> {LEAD_SOURCE_LABELS[lead.source]}</p><p><strong>Ø§Ù„Ù‡Ø§ØªÙ:</strong> {lead.phone}</p><p><strong>Ø§Ù„Ø¨Ø±ÙŠØ¯:</strong> {lead.email||'ØºÙŠØ± Ù…Ø³Ø¬Ù„'}</p><p><strong>Ø´Ø±ÙƒØ© Ø§Ù„ØªØ£Ù…ÙŠÙ†:</strong> {lead.preferredInsurerName||'ØºÙŠØ± Ù…Ø­Ø¯Ø¯Ø©'}</p><p><strong>Ø§Ù„Ù‚ÙŠÙ…Ø© Ø§Ù„Ù…ØªÙˆÙ‚Ø¹Ø©:</strong> {Number(lead.estimatedValue||0).toLocaleString('ar-EG')} Ø¬Ù†ÙŠÙ‡</p></section>
  {lead.stage!=='won'&&lead.stage!=='lost'&&<section className="card"><h2>Ø§Ù„Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø§Ù„Ù…ØªØ§Ø­Ø©</h2>{allowed.includes('lost')&&<textarea value={lostReason} onChange={e=>setLostReason(e.target.value)} placeholder="Ø³Ø¨Ø¨ ÙÙ‚Ø¯Ø§Ù† Ø§Ù„ÙØ±ØµØ©"/>}<div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{allowed.map(s=><button key={s} disabled={saving} onClick={()=>void move(s)}>{s==='won'?<CheckCircle2 size={16}/>:s==='lost'?<XCircle size={16}/>:null} Ø§Ù„Ø§Ù†ØªÙ‚Ø§Ù„ Ø¥Ù„Ù‰ {LEAD_STAGE_LABELS[s]}</button>)}</div></section>}
  {lead.stage==='won'&&<section className="card"><h2>ÙØ±ØµØ© Ù†Ø§Ø¬Ø­Ø©</h2>{lead.clientId?<Link to={`/clients/${lead.clientId}`}>ÙØªØ­ Client 360</Link>:<button className="primary-button" disabled={saving} onClick={()=>void convert()}>ØªØ­ÙˆÙŠÙ„ Ø¥Ù„Ù‰ Ø¹Ù…ÙŠÙ„</button>}</section>}
  <section className="card"><h2>Ù…Ù‡Ù…Ø© Ù…ØªØ§Ø¨Ø¹Ø©</h2><form onSubmit={addTask} style={{display:'grid',gap:8}}><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Ø¹Ù†ÙˆØ§Ù† Ø§Ù„Ù…Ù‡Ù…Ø©" required/><input type="date" value={taskDue} onChange={e=>setTaskDue(e.target.value)} required/><button disabled={saving}>Ø¥Ù†Ø´Ø§Ø¡ Ù…Ù‡Ù…Ø© Ù…Ø±ØªØ¨Ø·Ø©</button></form></section>
  <section className="card"><h2>Ø§Ù„Ù…Ù„Ø§Ø­Ø¸Ø§Øª</h2><textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5}/><button disabled={saving} onClick={()=>void saveNotes()}><Save size={16}/> Ø­ÙØ¸ Ø§Ù„Ù…Ù„Ø§Ø­Ø¸Ø§Øª</button></section>
  <section className="card"><h2>Ø³Ø¬Ù„ Ø§Ù„Ù†Ø´Ø§Ø·</h2>{acts.length===0?<p>Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ù†Ø´Ø§Ø· Ù…Ø³Ø¬Ù„.</p>:<div style={{display:'grid',gap:8}}>{acts.map(a=><div key={a.id}><strong>{a.message}</strong></div>)}</div>}</section>
 </div>;
}