import { useEffect, useState, type FormEvent } from 'react';
import { Save, X } from 'lucide-react';
import { updateClientProfile, type ClientEditInput } from './client-edit.service';
import type { InsuranceClient } from '../../types/client';

type Props={client:InsuranceClient;organizationId:string;onCancel:()=>void;onUpdated:()=>void};
export default function ClientEditForm({client,organizationId,onCancel,onUpdated}:Props){
 const [form,setForm]=useState<ClientEditInput>({name:client.name,type:client.type,status:client.status,phone:client.phone||'',email:client.email||'',city:client.city||'',address:client.address||'',notes:client.notes||''});
 const [saving,setSaving]=useState(false);const [error,setError]=useState('');
 useEffect(()=>setForm({name:client.name,type:client.type,status:client.status,phone:client.phone||'',email:client.email||'',city:client.city||'',address:client.address||'',notes:client.notes||''}),[client]);
 const set=<K extends keyof ClientEditInput>(key:K,value:ClientEditInput[K])=>setForm(v=>({...v,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();setError('');setSaving(true);try{await updateClientProfile(client.id,organizationId,form);onUpdated();}catch(err){setError(err instanceof Error&&err.message==='CLIENT_NAME_REQUIRED'?'اسم العميل مطلوب.':'تعذر حفظ التعديلات. حاول مرة أخرى.')}finally{setSaving(false)}}
 return <div className="client-edit-backdrop" role="presentation"><section className="client-edit-sheet" dir="rtl" role="dialog" aria-modal="true" aria-labelledby="client-edit-title"><header><div><span className="eyebrow">Client Profile</span><h2 id="client-edit-title">تعديل بيانات العميل</h2></div><button type="button" onClick={onCancel} aria-label="إغلاق"><X/></button></header><form onSubmit={submit}><div className="client-edit-grid"><label><span>اسم العميل *</span><input required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label><span>نوع العميل</span><select value={form.type} onChange={e=>set('type',e.target.value as ClientEditInput['type'])}><option value="individual">فرد</option><option value="company">شركة</option></select></label><label><span>الحالة</span><select value={form.status} onChange={e=>set('status',e.target.value as ClientEditInput['status'])}><option value="active">نشط</option><option value="prospect">محتمل</option><option value="inactive">غير نشط</option></select></label><label><span>الهاتف</span><input value={form.phone||''} onChange={e=>set('phone',e.target.value)} inputMode="tel"/></label><label><span>البريد الإلكتروني</span><input type="email" value={form.email||''} onChange={e=>set('email',e.target.value)}/></label><label><span>المدينة</span><input value={form.city||''} onChange={e=>set('city',e.target.value)}/></label><label className="wide"><span>العنوان</span><input value={form.address||''} onChange={e=>set('address',e.target.value)}/></label><label className="wide"><span>الملاحظات</span><textarea value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></label></div>{error&&<p className="client-edit-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onCancel} disabled={saving}>إلغاء</button><button type="submit" className="primary-button" disabled={saving}><Save/>{saving?'جارٍ الحفظ...':'حفظ التعديلات'}</button></footer></form></section></div>;
}
