import { useState, type FormEvent } from 'react';
import { createClient } from './client.service';
import { useAuth } from '../auth/auth-context';
import type { ClientInput, ClientStatus, ClientType } from '../../types/client';
const initial:ClientInput={type:'individual',status:'active',name:'',email:'',phone:'',nationalId:'',taxId:'',industry:'',city:'',address:'',notes:''};
export default function ClientForm({onCreated,onCancel}:{onCreated:()=>void;onCancel:()=>void}){
 const {user,profile}=useAuth();const [form,setForm]=useState(initial);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const set=(key:keyof ClientInput,value:string)=>setForm(v=>({...v,[key]:value}));
 async function submit(e:FormEvent){e.preventDefault();if(!user||!profile)return;setBusy(true);setError('');try{await createClient(form,profile.organizationId,user.uid);onCreated();}catch{setError('تعذر حفظ العميل. تحقق من اتصال Firestore والصلاحيات.');}finally{setBusy(false)}}
 return <div className="modal-backdrop"><section className="modal" dir="rtl"><header><div><span className="eyebrow">Insurance CRM</span><h2>إضافة عميل جديد</h2></div><button onClick={onCancel} className="icon-button">×</button></header><form className="client-form" onSubmit={submit}><div className="form-grid"><label>نوع العميل<select value={form.type} onChange={e=>set('type',e.target.value as ClientType)}><option value="individual">فرد</option><option value="company">شركة</option></select></label><label>الحالة<select value={form.status} onChange={e=>set('status',e.target.value as ClientStatus)}><option value="active">نشط</option><option value="prospect">محتمل</option><option value="inactive">غير نشط</option></select></label><label className="wide">اسم العميل *<input required value={form.name} onChange={e=>set('name',e.target.value)} /></label><label>الهاتف<input value={form.phone} onChange={e=>set('phone',e.target.value)} /></label><label>البريد الإلكتروني<input type="email" value={form.email} onChange={e=>set('email',e.target.value)} /></label><label>{form.type==='company'?'الرقم الضريبي':'الرقم القومي'}<input value={form.type==='company'?form.taxId:form.nationalId} onChange={e=>set(form.type==='company'?'taxId':'nationalId',e.target.value)} /></label><label>المدينة<input value={form.city} onChange={e=>set('city',e.target.value)} /></label><label className="wide">العنوان<input value={form.address} onChange={e=>set('address',e.target.value)} /></label><label className="wide">ملاحظات<textarea value={form.notes} onChange={e=>set('notes',e.target.value)} /></label></div>{error&&<p className="form-error">{error}</p>}<footer><button type="button" className="secondary-button" onClick={onCancel}>إلغاء</button><button className="primary-button" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ العميل'}</button></footer></form></section></div>
}
